### ISSUE TITLE
Add support for external properties

### ISSUE THREAD

**Issue by ldziedziul** [q-programming/tasq#2]
It would be great if one could change configuration without recompilation

**Comment by khobar** [comment]
Added support for properties changing 
TASQ-215 [https://github.com/q-programming/tasq/commit/ebd0f1e6305da554b6edec9f540c5bc1b5ac1792]
TASQ-223 [https://github.com/q-programming/tasq/commit/41f189819a2f32949aff13e60556e3ec21d4f79c]

**Comment by khobar** [comment]
Added support for properties changing 
TASQ-215 [https://github.com/q-programming/tasq/commit/ebd0f1e6305da554b6edec9f540c5bc1b5ac1792]
TASQ-223 [https://github.com/q-programming/tasq/commit/41f189819a2f32949aff13e60556e3ec21d4f79c]
